server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

jwt_secret: "{{ secret '/run/secrets/authelia_jwt_secret' }}"

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id

access_control:
  default_policy: one_factor
  rules:
    - domain:
        - helios.lan
        - ians-mac-mini.tailfc238d.ts.net
      policy: one_factor

session:
  secret: "{{ secret '/run/secrets/authelia_session_secret' }}"
  cookies:
    - name: helios_session
      domain: helios.lan
      authelia_url: https://helios.lan/auth
      expiration: 12h
      inactivity: 4h
    - name: helios_session_ts
      domain: ians-mac-mini.tailfc238d.ts.net
      authelia_url: https://ians-mac-mini.tailfc238d.ts.net/auth
      expiration: 12h
      inactivity: 4h

storage:
  encryption_key: "{{ secret '/run/secrets/authelia_storage_key' }}"
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
