server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    large_client_header_buffers 4 16k;

    # SPA routing - serve index.html for all paths
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
