db_password: ENC[AES256_GCM,data:f+wmsiBcwyPSp96k4psmyMl8dFxy6PlHCeG4g+BdCTRxomAXvLq9vXQPHhM5wxS7esevWLXEqfbs290ju5Zx7g==,iv:tg9Z60kc/B+GQXZqWHCtJ/rrLImXQ48nfvnRNDvpBMc=,tag:/aAY3xGNchqCNf0LsOHvwA==,type:str]
authelia_jwt_secret: ENC[AES256_GCM,data:T4MQotGzoLbaX17TGbAWXAzVfSW0cj8HmEa89Hu90Pmb8PbpMjE2GnBb07eVg/biKN+ogW9Cf+W4kms3d7vQ/g==,iv:b59RrmNlFa3lF/t4jOb1rtNDrcZd9VoA4JEZosjK8Z4=,tag:3LMsxk0qZXUyVWTO8DQ3Ug==,type:str]
authelia_session_secret: ENC[AES256_GCM,data:QcCJ/6mg3Mnq+RVUPhDo0aFr+zchqEvVnZ8fyJkMGoMDi6p5xTAUlPF7RrZvm/FqXc5qkwgTZgAAT0AAVFUyCg==,iv:4DpRWeANDwbBTCeylJhbrJOZLvjTMYIVg914ArIfaUw=,tag:Z4ehJsz6mJ2iwwx5zJx9Hg==,type:str]
authelia_storage_key: ENC[AES256_GCM,data:hM517oT4mjBuWSpY0IPH5YMu9/5TcOVU3Azqode2JTkOloswFJCu6gkaSFpbqgLxeT8llqSuiT+kLruwx7F8hA==,iv:m4hRRDYehsS8oNdtLrejcsMshExCSXxG6rgWKVCEUak=,tag:21OhCHNmrZbhTCoaa19u+g==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:MzhlHaJlUr5gJjtK25bjSA==,iv:E19zBQ3JaXzjPfpUeowW08QU86jISpkBFLocXTkRs5k=,tag:7jP/9aC0aep9QiHvChUkog==,type:str]
hue_app_key_bradgate: ENC[AES256_GCM,data:hFj6vpxTom1PNX265FwBe7jVHOqk0KV+o6XFOkn0j3qPyygkUiC4UQ==,iv:+e/5UIDjOtclJ+YSyqwQlBVtZDXE5JxTxf3T2ObLEIQ=,tag:7jWASnSBuA5tCUlT0GvREg==,type:str]
hue_app_key_bradgate2: ENC[AES256_GCM,data:TCncTKgAvvlZDSK/Bwb46I2sI6Il+CjdnCu0QgpEcpODD4+3O3x8rw==,iv:xybmxQ0u4nSF0769+94FzV+ck/NY+hrSjbIR6Cjsy+8=,tag:P9tQHO3OiMZ19Hxf+RudKg==,type:str]
octopus_api_key: ENC[AES256_GCM,data:ID60Uauhq1MQDBw5r+x4miFmeqRbuq1uw5+4Uuazvu8oF8qcf39sBQ==,iv:Rr2vLeLLTkwDbGC1hgd8N98E0uwlMQ+M+yYePM5KlSM=,tag:xhhIeotlrKPcwBf3NVaQFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUlpQZjdWSmJNd2pvZjZO
            emV4MGJ4TVhnWTFicnRuZTFtKzlabEp1d1NFCnAwb2VENXJLd29LRmtjQityY0pz
            cVNuemlyNys0SWRsOS9sWGI3ZGZFTXMKLS0tIDJsSm5QWWE1ODFFZmxyUXZCSXE4
            a2p5WjNjVHdWaUF5bEMrNC9FUWJLSm8KqlL88UmLurkYoaNlSbpG15odTyJ8CnZS
            DqNgjIjg6VxfnJtXMYMBby9C5Zplq+uNEId5c7PylkOJNUt7v5M/NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12wzlmlk8y7h7xahfe8qh7lm0e2allh82l824hvuzzt596ghr9psqccmf84
    lastmodified: "2026-05-30T08:08:34Z"
    mac: ENC[AES256_GCM,data:Gbt/UhEl+vpj609U5D/Ri17JM3mE00tdi3tv7BeUnQ3Q4mayunaM4SVtJDgWNDknBWUAFYIFQWCKYk1HDhJnLvL9UpKY8oUYQH/NFTBNmJJjcFeVh3JTX5pYE/pbxyLKT3ONvU5m+Fp8FNmwTvRfz4aoOq8qKlHRYgZiFco3G+w=,iv:l/Oe5ZcqsXoJbR3kogJkfm3fApj69rJncmwtPUEnTGU=,tag:fxR+Kd+eacq6LRHCip8jSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
