apiVersion: 1

datasources:
  - name: Helios DB
    type: postgres
    url: db:5432
    database: helios
    user: helios
    secureJsonData:
      password: $GF_DATASOURCE_HELIOS_DB_PASSWORD
    jsonData:
      sslmode: disable
      timescaledb: true
    isDefault: true

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: false
